version: "3.5"

services:
  influxdb:
    image: influxdb:1.8
    container_name: librenms_influxdb
    restart: unless-stopped
    volumes:
      - influxdb_data:/var/lib/influxdb
    ports:
      - "8086:8086"

  grafana:
    image: grafana/grafana:latest
    container_name: librenms_grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana

volumes:
  influxdb_data:
  grafana_data:

